const PROJECT_NAME = "homescreen";

const INITIAL_ITEMS = [
  {
    id: "youtube",
    order: 1,
    name: "YouTube",
    type: "shortcut",
    parentId: null,
    path: [{ id: null, name: "Root" }],
    url: "https://www.youtube.com/",
    icon: null,
  },
  {
    id: "facebook",
    order: 2,
    name: "Facebook",
    type: "shortcut",
    parentId: null,
    path: [{ id: null, name: "Root" }],
    url: "https://www.facebook.com/",
    icon: null,
  },
  {
    id: "instagram",
    order: 3,
    name: "Instagram",
    type: "shortcut",
    parentId: null,
    path: [{ id: null, name: "Root" }],
    url: "https://www.instagram.com/",
    icon: null,
  },
  {
    id: "x",
    order: 4,
    name: "X",
    type: "shortcut",
    parentId: null,
    path: [{ id: null, name: "Root" }],
    url: "https://x.com/",
    icon: null,
  },
  {
    id: "reddit",
    order: 5,
    name: "Reddit",
    type: "shortcut",
    parentId: null,
    path: [{ id: null, name: "Root" }],
    url: "https://www.reddit.com/",
    icon: null,
  },
  {
    id: "weather",
    order: 6,
    name: "AccuWeather",
    type: "shortcut",
    parentId: null,
    path: [{ id: null, name: "Root" }],
    url: "https://www.accuweather.com/",
    icon: null,
  },
  {
    id: "spotify",
    order: 7,
    name: "Spotify Web Player",
    type: "shortcut",
    parentId: null,
    path: [{ id: null, name: "Root" }],
    url: "https://open.spotify.com/",
    icon: null,
  },
  {
    id: "translate",
    order: 8,
    name: "Google Translate",
    type: "shortcut",
    parentId: null,
    path: [{ id: null, name: "Root" }],
    url: "https://translate.google.com/",
    icon: null,
  },
];
